name: spt-worker
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy<2.0
  - h5py
  - pyyaml
  - scipy
  - ninja
  - tensorboard
  - pip:
    - packaging
    - addict
    - timm
    - plyfile
    - open3d
    - tqdm