# NVIDIA GPU (CUDA 11.8)
name: spt-env

channels:
  - pytorch
  - pyg
  - nvidia
  - conda-forge
  - anaconda
  - defaults

dependencies:
  - python=3.11
  - pip
  - pytorch-cuda=11.8
  - pytorch=2.1.0=*cuda*
  - torchvision=0.16.0
  - torchaudio=2.1.0
  - numpy<2.0
  - nvidia::cuda-compiler=11.8
  - pyg
  - addict
  - timm
  - ninja
  - h5py
  - pyyaml
  - scipy
  - plyfile
  - tensorboard
  - pip:
    - packaging
    - spconv-cu118
    - open3d
