# CPU only environment

name: spt-env_cpu

channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults

dependencies:
  - python=3.11
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - addict
  - timm
  - ninja
  - h5py
  - pyyaml
  - scipy
  - plyfile
  - tensorboard
  - pip:
    - torch-scatter
    - spconv
    - packaging
    - open3d
